// Launcher install + SessionStart reconcile. The bin wrapper no longer points
// at a versioned plugin path (which dies on the next auto-update + cache GC);
// it calls a stable resolver copy in STATE_DIR that picks the highest valid
// registered plugin root at call time. Every SessionStart re-registers the root
// the host actually loaded, so a stale launcher heals itself with zero steps.
import {
  appendFileSync, chmodSync, existsSync, lstatSync, mkdirSync, readFileSync,
  readlinkSync, renameSync, writeFileSync,
} from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { STATE_DIR, resolverPath, registryFile } from "./config.mjs";
import { validateRoot } from "../resolver.mjs";

const MARKER = "Generated by cc-usage";

// tools/ dir = two up from tools/core/launcher.mjs; plugin root = one above.
export const toolDir = dirname(dirname(fileURLToPath(import.meta.url)));
export function pluginRoot() { return dirname(toolDir); }

export function launcherDir() {
  if (process.env.CC_USAGE_BIN_DIR) return process.env.CC_USAGE_BIN_DIR;
  if (platform() === "win32") {
    return join(process.env.LOCALAPPDATA || join(homedir(), "AppData", "Local"), "cc-usage", "bin");
  }
  return join(homedir(), ".local", "bin");
}

export function launcherPath() {
  return join(launcherDir(), platform() === "win32" ? "cc-usage.cmd" : "cc-usage");
}

function atomicWrite(path, content, mode) {
  const tmp = `${path}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tmp, content, mode === undefined ? undefined : { mode });
  renameSync(tmp, path);
}

// True only for a launcher we created: the pre-resolver symlink into a
// cc-usage tools/cc-usage, or the new marker-bearing wrapper file. Anything
// else is a foreign file we must never touch.
export function ownsLauncher(path) {
  let stat;
  try { stat = lstatSync(path); } catch { return false; }
  if (stat.isSymbolicLink()) {
    try {
      return /(?:^|[\\/])cc-usage(?:[\\/].*)?[\\/]tools[\\/]cc-usage$/.test(readlinkSync(path));
    } catch { return false; }
  }
  try { return readFileSync(path, "utf8").includes(MARKER); } catch { return false; }
}

// Record this root in the runtime registry, dropping dead and duplicate
// entries. Atomic so concurrent session starts can't tear the file.
export function registerRoot(root, version) {
  mkdirSync(STATE_DIR, { recursive: true });
  let entries = [];
  try {
    const parsed = JSON.parse(readFileSync(registryFile, "utf8"));
    if (Array.isArray(parsed.entries)) entries = parsed.entries;
  } catch { /* fresh registry */ }
  entries = entries.filter((e) => e && e.root !== root && validateRoot(e.root));
  entries.push({ root, version, registeredAt: new Date().toISOString() });
  atomicWrite(registryFile, `${JSON.stringify({ schemaVersion: 1, entries }, null, 2)}\n`, 0o600);
}

// Keep the stable resolver copy in STATE_DIR current with this plugin version.
export function refreshResolver(root) {
  mkdirSync(STATE_DIR, { recursive: true });
  const source = readFileSync(join(root, "tools", "resolver.mjs"), "utf8");
  let current = null;
  try { current = readFileSync(resolverPath, "utf8"); } catch { /* absent */ }
  if (current !== source) atomicWrite(resolverPath, source, 0o755);
  return resolverPath;
}

// Point the bin wrapper(s) at the resolver. Idempotent; foreign files untouched.
export function healWrappers(resolver) {
  const dir = launcherDir();
  mkdirSync(dir, { recursive: true });
  if (platform() === "win32") {
    const cmdPath = join(dir, "cc-usage.cmd");
    const psPath = join(dir, "cc-usage.ps1");
    if (!existsSync(cmdPath) || ownsLauncher(cmdPath)) {
      atomicWrite(cmdPath, `@echo off\r\nrem ${MARKER}\r\nnode "${resolver.replaceAll("%", "%%")}" %*\r\n`);
    }
    if (!existsSync(psPath) || ownsLauncher(psPath)) {
      atomicWrite(psPath, `# ${MARKER}\n& node '${resolver.replaceAll("'", "''")}' @args\nexit $LASTEXITCODE\n`);
    }
    return;
  }
  const shimPath = join(dir, "cc-usage");
  // lstat, not existsSync: a DANGLING foreign symlink makes existsSync false and
  // would sneak past the ownership guard and get clobbered.
  let present = true;
  try { lstatSync(shimPath); } catch { present = false; }
  if (present && !ownsLauncher(shimPath)) return; // foreign — hands off
  const shim = `#!/bin/sh\n# ${MARKER}\nexec node "${resolver.replaceAll('"', '\\"')}" "$@"\n`;
  let current = null;
  try {
    if (!lstatSync(shimPath).isSymbolicLink()) current = readFileSync(shimPath, "utf8");
  } catch { /* absent */ }
  if (current !== shim) { atomicWrite(shimPath, shim, 0o755); chmodSync(shimPath, 0o755); }
}

// A git working tree is a developer checkout, not an installed release. Never
// register one by default: the resolver also drives the unattended daily sync,
// and a dirty or half-edited tree must not silently become the runtime. Set
// CC_USAGE_REGISTER_DEV=1 to opt in while developing.
export function isDevCheckout(root) {
  if (process.env.CC_USAGE_REGISTER_DEV) return false;
  // Look at the plugin dir and at most two ancestors — enough to spot a repo
  // checkout (<repo>/.git with the plugin one or two levels down) but NOT
  // enough to reach the install path's distant ancestors. Walking further
  // would find ~/.claude/.git on every machine whose config dir is a dotfiles
  // repo and silently disable the whole mechanism. Stop at the config dir too.
  const configDir = process.env.CLAUDE_CONFIG_DIR || join(homedir(), ".claude");
  let dir = root;
  for (let i = 0; i < 3; i += 1) {
    if (dir === configDir) return false;
    if (existsSync(join(dir, ".git"))) return true;
    const up = dirname(dir);
    if (up === dir) break;
    dir = up;
  }
  return false;
}

// Best-effort diagnostic. A reconcile that skips silently is undiagnosable —
// the launcher and the unattended sync just quietly stay stale.
function trace(reason) {
  try {
    mkdirSync(STATE_DIR, { recursive: true });
    appendFileSync(join(STATE_DIR, "hook.err"), `${new Date().toISOString()} reconcile skipped: ${reason}\n`);
  } catch { /* best effort */ }
}

// SessionStart duty: register → refresh resolver → heal wrappers. Never throws.
export function reconcile() {
  try {
    const root = pluginRoot();
    const version = validateRoot(root);
    if (!version) { trace(`${root} is not a valid plugin root (half-written or foreign)`); return; }
    if (isDevCheckout(root)) {
      trace(`${root} looks like a dev checkout (set CC_USAGE_REGISTER_DEV=1 to register it)`);
      return;
    }
    registerRoot(root, version);
    healWrappers(refreshResolver(root));
  } catch (error) { trace(`unexpected: ${error && error.message}`); }
}

// Explicit `cc-usage install-launcher`: same reconcile, but loud and strict.
export function installLauncher() {
  const path = launcherPath();
  if (existsSync(path) && !ownsLauncher(path)) {
    const e = new Error(`refusing to replace an unrecognized launcher: ${path}`);
    e.exitCode = 1; throw e;
  }
  const root = pluginRoot();
  const version = validateRoot(root);
  if (!version) {
    const e = new Error(`not a valid cc-usage plugin root: ${root}`);
    e.exitCode = 1; throw e;
  }
  registerRoot(root, version);
  healWrappers(refreshResolver(root));
  process.stdout.write(`Installed launcher: ${path}\n`);
  const dir = launcherDir();
  const norm = (v) => v.replace(/[\\/]+$/, "");
  if (!(process.env.PATH || "").split(":").map(norm).includes(norm(dir))) {
    process.stderr.write(`Add ${dir} to PATH to call cc-usage directly.\n`);
  }
  return path;
}
